export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FILTER_BY = "FILTER_BY";
export const ORDER_BY = "ORDER_BY";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const IS_SEARCH="IS_SEARCH";
